export const CREATE_CARD  = 'CREATE_CARD'
export const EDIT_CARD    = 'EDIT_CARD'
export const DELETE_CARD  = 'DELETE_CARD'
export const CREATE_PANEL = 'CREATE_PANEL'
export const EDIT_PANEL   = 'EDIT_PANEL'